### ISSUE TITLE
Does not take Extra's into account

### ISSUE THREAD

**Issue by IncreaseComputers** [dinoperovic/django-salesman-stripe#2] opened 2022-04-22 22:12 UTC
If you add extras to the cart for shipping etc, the payment provider does not take them into account when calculating the total

**Comment by dinoperovic** [comment] 2022-04-23 06:18
@IncreaseComputers Yes you are correct, looks like I've missed that.

The issue is that `extra_rows` can contain both the added charges and discounts/deductions of price which can't be sent to Stripe directly in `line_items`. Stripe does however support separate discount and shipping definition that can be sent, but this can be really specific to the shop implementation and should be added by overriding the `get_stripe_session_data` manually.

Looking at this now seems that the only way to send full charges is to have a single Stripe line item for the entire basket/order.

I will consider making this the default and having separate line items will require overriding the provider.

**Comment by dinoperovic** [comment] 2022-04-25 08:12
This is fixed and released in `v0.1.5`

**Closed as completed by dinoperovic** 2022-04-25 08:12 UTC
Labels: bug
